services:
  backend:
    build: ./Backend
    ports:
      - 8001:8001
    environment:
      - DB_USER=postgres
      - DB_PASS=admin
      - DB_NAME=DB_usuarioApi
      - DB_HOST=db

    volumes:
      - ./Backend:/app-backend
    
    container_name: WebAPI_backend
    restart: always
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      
    restart: always